{
 "title": "DAppNode ETH2 prater",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total Validator Balance (ETH)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"})",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Earnings (ETH)",
   "type": "stat",
   "description": "Total ETH return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"})-(count(validator_balance{service=\"validator.prater.dappnode\"} > 16 and validator_statuses{service=\"validator.prater.dappnode\"} == 3)*32)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "singlestat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(validator_balance{service=\"validator.prater.dappnode\"}) - (count(validator_balance{service=\"validator.prater.dappnode\"} > 16 and validator_statuses{service=\"validator.prater.dappnode\"} == 3)*32))/(count(validator_balance{service=\"validator.prater.dappnode\"} > 16 and validator_statuses{service=\"validator.prater.dappnode\"} == 3)*32)  "
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",service=\"beacon-chain.prater.dappnode\"}"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{service=\"beacon-chain.prater.dappnode\"} / beacon_prev_epoch_active_gwei{service=\"beacon-chain.prater.dappnode\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{service=\"beacon-chain.prater.dappnode\"}/32) - beacon_finalized_epoch{service=\"beacon-chain.prater.dappnode\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{service=\"beacon-chain.prater.dappnode\"} / beacon_prev_epoch_active_gwei{service=\"beacon-chain.prater.dappnode\"} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Total Validator Balance (USD)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of ETH in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ethusd ", "legendFormat": "ethusd" },
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"})",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Total Earnings (USD)",
   "type": "stat",
   "description": "Total earnings in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"})-(count(validator_balance{service=\"validator.prater.dappnode\"} > 16 and validator_statuses{service=\"validator.prater.dappnode\"} == 3)*32)",
     "legendFormat": "total_balance"
    },
    { "expr": "ethusd", "legendFormat": "ethusd" }
   ]
  },
  {
   "title": "ETH Price (USD)",
   "type": "stat",
   "description": "Price of ETH in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ethusd", "legendFormat": "ethusd" }
   ]
  },
  {
   "title": "Avg. Last Inclusion Distance",
   "type": "stat",
   "description": "Average inclusion distance of the last attestations by all validators.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(validator_inclusion_distance)"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{service=\"beacon-chain.prater.dappnode\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {service=\"beacon-chain.prater.dappnode\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Local Validators",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 1h != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) + (32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 1h > 16))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 1d != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) + (32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 7d != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) + (32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 7d > 16))"
    }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "format": "ETH",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 30d != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) + (32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 30d > 16))"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",service=\"beacon-chain.prater.dappnode\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",service=\"beacon-chain.prater.dappnode\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",service=\"beacon-chain.prater.dappnode\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\",service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{service=\"beacon-chain.prater.dappnode\", state=\"Active\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 1h != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) +\t(32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 1h > 16)))/(32 * avg_over_time(count(validator_balance{service=\"validator.prater.dappnode\"} > 16)[1h:]))) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 1d != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) +\t(32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 1d > 16)))/(32 * avg_over_time(count(validator_balance{service=\"validator.prater.dappnode\"} > 16)[1d:]))) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 7d != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) +\t(32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 7d > 16)))/(32 * avg_over_time(count(validator_balance{service=\"validator.prater.dappnode\"} > 16)[7d:]))) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Monthly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{service=\"validator.prater.dappnode\"}) - sum(validator_balance{service=\"validator.prater.dappnode\"} offset 30d != 0) - (32 * count(validator_balance{service=\"validator.prater.dappnode\"} > 16)) +\t(32 * count(validator_balance{service=\"validator.prater.dappnode\"} offset 30d > 16)))/(32 * avg_over_time(count(validator_balance{service=\"validator.prater.dappnode\"} > 16)[30d:]))) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "singlestat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\",service=\"beacon-chain.prater.dappnode\"} / validator_count{state=\"Active\",service=\"beacon-chain.prater.dappnode\"} / 1000000000",
     "legendFormat": "eth"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\",service=\"beacon-chain.prater.dappnode\"}/4)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\",service=\"beacon-chain.prater.dappnode\"}/4)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table-old",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") ",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_proposals{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_aggregations{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_attestations{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_aggregations{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{service=\"validator.prater.dappnode\"}), \"pubkey\", \"$1\", \"pubkey_short\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_inclusion_distance{service=\"validator.prater.dappnode\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Beacon Uptime",
   "type": "singlestat",
   "description": "The length of time the beacon chain process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{service=\"beacon-chain.prater.dappnode\"})/3600"
    }
   ]
  },
  {
   "title": "Beacon Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{service=\"beacon-chain.prater.dappnode\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{service=\"beacon-chain.prater.dappnode\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Validator Uptime",
   "type": "singlestat",
   "description": "The length of time the validator process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{service=\"validator.prater.dappnode\"})/3600"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{service=\"validator.prater.dappnode\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{service=\"validator.prater.dappnode\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Server",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "graph",
   "description": "Beacon chain and validator memory usage on the server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"beacon-chain.prater.dappnode\"}",
     "legendFormat": "beacon memory"
    },
    {
     "expr": "process_resident_memory_bytes{service=\"validator.prater.dappnode\"}",
     "legendFormat": "validator memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"system\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=\"nodeexporter\"}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=\"nodeexporter\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{id=\"/\",interface!~\"br.*|lo\"}[1m]))*8 / 1048576",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{id=\"/\",interface!~\"br.*|lo\"}[1m]))*8 /1048576",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"nodeexporter\"})-sum(node_filesystem_avail_bytes{job=\"nodeexporter\"}))/sum(node_filesystem_size_bytes{job=\"nodeexporter\"})",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"nodeexporter\"} - node_memory_MemFree_bytes{job=\"nodeexporter\"} - node_memory_Buffers_bytes{job=\"nodeexporter\"} - node_memory_Cached_bytes{job=\"nodeexporter\"} - node_memory_SwapCached_bytes{job=\"nodeexporter\"} - node_memory_Slab_bytes{job=\"nodeexporter\"} - node_memory_PageTables_bytes{job=\"nodeexporter\"} - node_memory_VmallocUsed_bytes{job=\"nodeexporter\"} ) or ( node_memory_MemTotal{job=\"nodeexporter\"} - node_memory_MemFree{job=\"nodeexporter\"} - node_memory_Buffers{job=\"nodeexporter\"} - node_memory_Cached{job=\"nodeexporter\"} - node_memory_SwapCached{job=\"nodeexporter\"} - node_memory_Slab{job=\"nodeexporter\"} - node_memory_PageTables{job=\"nodeexporter\"} - node_memory_VmallocUsed{job=\"nodeexporter\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"nodeexporter\"} or node_memory_Buffers{job=\"nodeexporter\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"nodeexporter\"} or node_memory_Cached{job=\"nodeexporter\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"} or node_memory_MemFree{job=\"nodeexporter\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"nodeexporter\"} or node_memory_Slab{job=\"nodeexporter\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",job=\"nodeexporter\",sensor=\"temp1\"}",
     "legendFormat": "cpu temp"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"google\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_duration_seconds{instance=\"cloudflare\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_duration_seconds{instance=\"remote\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_duration_seconds{instance=\"dyndns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}